### ISSUE TITLE
The yellow button should appear earlier

### ISSUE THREAD

**Issue by UrielOfir** [Rivki7/Maakaf-Landing-Page#3]
Now the button appear only after the animation of the text,
I think it should appear at the upload of the site and don't wait for the headline text.

Users can start scroll down and miss the button.

**Comment by Rivki7** [comment]
I think it's better that the button appears after the animation of the text, it looks weird to have the button before the text animation.
Even if the users miss the button they can still see the 'Join us' section when they scroll.

**Comment by UrielOfir** [comment]
Thank you for your answer :)
